#ifndef MANIFESTCONFIG_H
#define MANIFESTCONFIG_H

#define LORETHUNK_CONFIG_VARG_MAX 100

#define LORETHUNK_CONFIG_GUEST_FUNCTION_STATIC_LINK

// #define LORETHUNK_CONFIG_HOST_FUNCTION_STATIC_LINK

#endif // MANIFESTCONFIG_H
