#ifndef LORE_TLCAPI_DOCUMENTCONTEXT_H
#define LORE_TLCAPI_DOCUMENTCONTEXT_H

#include <map>
#include <string>
#include <cassert>
#include <set>
#include <array>
#include <vector>
#include <memory>

#include <lorelei/ClangExtras/SourceLineList.h>
#include <lorelei/TLCApi/ProcSnippet.h>
#include <lorelei/TLCApi/Pass.h>
#include <lorelei/TLCApi/Global.h>

namespace clang {
    class CompilerInstance;
}

namespace lore::tool::TLC {

    class ManifestFile;
    class Pass;
    class ProcAliasMaker;

    /// DocumentContext - Runtime state container for one TLC `generate` invocation.
    ///
    /// Responsibilities:
    /// 1. Hold immutable input metadata (mode, source file path, manifest stat reference).
    /// 2. Own mutable proc list consumed by TLC passes.
    /// 3. Own document-level source fragments emitted by the generation pipeline.
    /// 4. Accept pre-collected AST metadata from command/main and apply it to procs.
    ///
    /// Non-responsibilities:
    /// 1. AST matching and clang traversal.
    /// 2. Command-line parsing.
    class LORETLCAPI_EXPORT DocumentContext {
    public:
        enum Mode {
            Guest = 0,
            Host = 1,
        };

        struct RequestedProcData {
            std::array<std::set<std::string>, ProcSnippet::NumKinds> functions;
            std::map<std::string /* signature */, std::string /* name */> callbacks;
        };

        struct DocumentSource {
            std::map<std::string, std::string> properties;
            SourceLineList<> head;
            SourceLineList<> tail;
        };

        struct FunctionPointerTypeInfo {
            clang::QualType type;
            std::string name;
        };

        DocumentContext();
        ~DocumentContext();

        inline void initialize(Mode mode, std::string preIncludeFileName, std::string mainFileName,
                               RequestedProcData interestedProcData) {
            m_mode = mode;
            m_preIncludeFileName = std::move(preIncludeFileName);
            m_mainFileName = std::move(mainFileName);
            m_requestedProcData = std::move(interestedProcData);
        }

        bool beginSourceFileAction(clang::CompilerInstance &CI);
        llvm::Error handleTranslationUnit(clang::ASTContext &ast);
        llvm::Error endSourceFileAction();

        llvm::Error generateOutput(llvm::raw_ostream &os);

    public:
        inline Mode mode() const {
            return m_mode;
        }
        inline std::string preIncludeFileName() const {
            return m_preIncludeFileName;
        }
        inline std::string mainFileName() const {
            return m_mainFileName;
        }
        inline clang::ASTContext &ast() const {
            assert(m_ast != nullptr);
            return *m_ast;
        }

        /// Collected AST metadata.
        inline const std::map<std::string, const clang::FunctionDecl *> &
            functionDecls(ProcSnippet::Direction direction) const {
            return m_functionDecls[direction];
        }
        inline const std::map<std::string, FunctionPointerTypeInfo> &callbackTypes() const {
            return m_callbackTypes;
        }
        inline const std::map<std::string, const clang::VarDecl *> &varDecls() const {
            return m_varDecls;
        }

        /// Sources to generate.
        inline DocumentSource &source() {
            return m_source;
        }
        inline const DocumentSource &source() const {
            return m_source;
        }

        /// Proc snippets.
        inline std::map<std::string, ProcSnippet> &procs(ProcSnippet::Kind kind,
                                                         ProcSnippet::Direction direction) {
            return m_procs[kind][direction];
        }
        inline const std::map<std::string, ProcSnippet> &
            procs(ProcSnippet::Kind kind, ProcSnippet::Direction direction) const {
            return m_procs[kind][direction];
        }

    protected:
        // generateOutput helpers; each appends one section of the generated TU to `os`.
        void emitManifestPrologue(llvm::raw_ostream &os) const;
        llvm::Error emitExportedAliases(llvm::raw_ostream &os) const;
        void emitForeachMacros(llvm::raw_ostream &os) const;
        void emitProcTexts(llvm::raw_ostream &os, bool asDeclaration) const;
        void emitMissingComments(llvm::raw_ostream &os) const;

        Mode m_mode = Guest;
        std::string m_preIncludeFileName;
        std::string m_mainFileName;
        RequestedProcData m_requestedProcData;

        // AST data
        clang::ASTContext *m_ast = nullptr;
        std::array<std::map<std::string, const clang::FunctionDecl *>, ProcSnippet::NumDirections>
            m_functionDecls;
        std::map<std::string, FunctionPointerTypeInfo> m_callbackTypes;
        std::map<std::string, const clang::VarDecl *> m_varDecls;

        // Generated by passes
        DocumentSource m_source;
        std::array<std::array<std::map<std::string, ProcSnippet>, ProcSnippet::NumDirections>,
                   ProcSnippet::NumKinds>
            m_procs;

        // Helpers
        std::unique_ptr<ProcAliasMaker> m_procAliasMaker;

        // Cached pass instances
        std::array<std::map<int, Pass *>, Pass::NumPhases> m_passMaps;
        std::vector<std::unique_ptr<Pass>> m_passInstances;
    };

}

#endif // LORE_TLCAPI_DOCUMENTCONTEXT_H
