#!/usr/bin/env bash
#
# Clone and build lorelei-thunks against the installed lorelei, twice, into a uniform layout. Each
# side installs into the same flat prefix as lorelei (no per-repo subdir):
#   install         host side: the HTL (this machine's arch)
#   install/x86_64  guest side: the GTL (x86_64)
#
# The host build also generates both thunk sources and installs them, so the guest build compiles the
# guest source straight from THUNK_GEN_SOURCE_DIR without running TLC. lorelei-thunks builds only its
# stable thunks (zlib, lzma) by default, which are exactly the ones the end-to-end test runs and the
# only ones that build on every CI arch (SDL2's multiarch headers do not resolve on a cross arch), so
# no explicit thunk selection is needed here.
set -euo pipefail
: "${REPOS_DIR:?}"
: "${INSTALL_DIR:?}"

arch="$(uname -m)"
guest_extra=()
host_extra=()
if [ "$arch" = "x86_64" ] || [ "$arch" = "amd64" ]; then
    GUEST_CC=gcc
    GUEST_CXX=g++
elif [ "$arch" = "riscv64" ]; then
    # Our Canadian-cross toolchain (gcc 11.4, own sysroot); point it at the amd64 multiarch ffcall.
    GUEST_CC=x86_64-unknown-linux-gnu-gcc
    GUEST_CXX=x86_64-unknown-linux-gnu-g++
    guest_extra=(
        "-DCMAKE_C_FLAGS=-idirafter /usr/include"
        "-DCMAKE_CXX_FLAGS=-idirafter /usr/include"
        "-DCMAKE_EXE_LINKER_FLAGS=-L/usr/lib/x86_64-linux-gnu"
        "-DCMAKE_SHARED_LINKER_FLAGS=-L/usr/lib/x86_64-linux-gnu"
    )
    # The host build runs TLC, whose x86_64 guest generate cannot find x86_64 C++ headers natively;
    # point that parse at the toolchain (--gcc-toolchain / --sysroot), and add -idirafter /usr/include
    # so a thunk's own library header (e.g. zlib.h) is still found after the toolchain's own headers.
    # stat and the host generate parse natively, so leave them.
    tc=/opt/x86_64-unknown-linux-gnu
    host_extra=( "-DTHUNK_GTL_EXTRA_ARGS=--gcc-toolchain=$tc;--sysroot=$tc/x86_64-unknown-linux-gnu/sysroot;-idirafter;/usr/include" )
else
    GUEST_CC=x86_64-linux-gnu-gcc
    GUEST_CXX=x86_64-linux-gnu-g++
fi

cd "$REPOS_DIR"
# Track the thunks main branch.
THUNKS_BRANCH=main
if [ ! -d lorelei-thunks ]; then
    curl -fsSL "https://codeload.github.com/rover2024/lorelei-thunks/tar.gz/refs/heads/$THUNKS_BRANCH" | tar xz
    mv "lorelei-thunks-$THUNKS_BRANCH" lorelei-thunks
fi
cd lorelei-thunks

# Host side: the HTL (native). Runs the TLC and installs ThunkStat.json plus both generated sources.
cmake -B build -G Ninja \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR" \
    -Dqmsetup_DIR="$INSTALL_DIR/lib/cmake/qmsetup" \
    -Dlorelei_DIR="$INSTALL_DIR/lib/cmake/lorelei" \
    -DTHUNK_BUILD_HOST_TARGETS=TRUE \
    -DTHUNK_BUILD_GUEST_TARGETS=FALSE \
    "${host_extra[@]}"
cmake --build build --target install

# Guest side: the GTL (x86_64), reusing the sources generated by the host build (no TLC here), linked
# against the x86_64 lorelei.
cmake -B build-guest -G Ninja \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_C_COMPILER="$GUEST_CC" \
    -DCMAKE_CXX_COMPILER="$GUEST_CXX" \
    -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR/x86_64" \
    -Dqmsetup_DIR="$INSTALL_DIR/lib/cmake/qmsetup" \
    -Dlorelei_DIR="$INSTALL_DIR/x86_64/lib/cmake/lorelei" \
    -DTHUNK_GEN_SOURCE_DIR="$INSTALL_DIR/share/lorelei/thunks" \
    -DTHUNK_BUILD_HOST_TARGETS=FALSE \
    -DTHUNK_BUILD_GUEST_TARGETS=TRUE \
    "${guest_extra[@]}"
cmake --build build-guest --target install
