#!/usr/bin/env bash
#
# Clone and build lorelei-thunks against the installed lorelei, twice, into a uniform layout:
#   install/lorethunks         host side: the HTL (this machine's arch)
#   install/x86_64/lorethunks  guest side: the GTL (x86_64)
#
# The host build also generates both thunk sources and installs them, so the guest build compiles the
# guest source straight from THUNK_GEN_SOURCE_DIR without running TLC. Only the zlib thunk is built
# (SDL2 disabled) to keep the image small.
set -euo pipefail
: "${REPOS_DIR:?}"
: "${INSTALL_DIR:?}"

arch="$(uname -m)"
if [ "$arch" = "x86_64" ] || [ "$arch" = "amd64" ]; then
    GUEST_CC=gcc
    GUEST_CXX=g++
else
    GUEST_CC=x86_64-linux-gnu-gcc
    GUEST_CXX=x86_64-linux-gnu-g++
fi

cd "$REPOS_DIR"
if [ ! -d lorelei-thunks/.git ]; then
    git clone https://github.com/rover2024/lorelei-thunks.git
fi
cd lorelei-thunks

# Host side: the HTL (native). Runs the TLC and installs ThunkStat.json plus both generated sources.
cmake -B build -G Ninja \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR/lorethunks" \
    -Dqmsetup_DIR="$INSTALL_DIR/qmsetup/lib/cmake/qmsetup" \
    -Dlorelei_DIR="$INSTALL_DIR/lorelei/lib/cmake/lorelei" \
    -DTHUNK_BUILD_HOST_TARGETS=TRUE \
    -DTHUNK_BUILD_GUEST_TARGETS=FALSE \
    -DTHUNK_DISABLE_LIBRARIES=SDL2
cmake --build build --target install

# Guest side: the GTL (x86_64), reusing the sources generated by the host build (no TLC here), linked
# against the x86_64 lorelei.
cmake -B build-guest -G Ninja \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_C_COMPILER="$GUEST_CC" \
    -DCMAKE_CXX_COMPILER="$GUEST_CXX" \
    -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR/x86_64/lorethunks" \
    -Dqmsetup_DIR="$INSTALL_DIR/qmsetup/lib/cmake/qmsetup" \
    -Dlorelei_DIR="$INSTALL_DIR/x86_64/lorelei/lib/cmake/lorelei" \
    -DTHUNK_GEN_SOURCE_DIR="$INSTALL_DIR/lorethunks/share/lorelei/thunks" \
    -DTHUNK_BUILD_HOST_TARGETS=FALSE \
    -DTHUNK_BUILD_GUEST_TARGETS=TRUE \
    -DTHUNK_DISABLE_LIBRARIES=SDL2
cmake --build build-guest --target install
