// SPDX-License-Identifier: MIT

#include <string>
#include <cstdlib>

#include <llvm/Support/Program.h>
#include <clang/Tooling/CommonOptionsParser.h>
#include <clang/Tooling/Tooling.h>

#include <lorelei/Tools/ToolUtils/TypeUtils.h>
#include <lorelei/Tools/TLCApi/Utils/ManifestStatistics.h>

#include "Utils/ASTConsumers.h"
#include "Utils/SourceStatistics.h"

// TODO: Rename to Probe


using namespace clang;
using namespace clang::tooling;

namespace cl = llvm::cl;

namespace lore::tool::command::stat {

    struct GlobalContext {
        /// Global states
        SmallString<128> initialCwd;
        std::string manifestStatPath;
        std::string outputPath;

        /// Runtime
        std::set<std::string> requestedSignatures;
        HLR::SourceStatistics sourceStat;
    };

    static GlobalContext &g_ctx() {
        static GlobalContext instance;
        return instance;
    }

    class MyASTFrontendAction : public ASTFrontendAction {
    public:
        void EndSourceFileAction() override {
            auto &CI = getCompilerInstance();
            if (CI.getLangOpts().CPlusPlus) {
                llvm::errs() << "error: HLR stat only supports C input. "
                                "Use C language flags (e.g. -xc -std=c11).\n";
                std::exit(1);
            }
            auto &SM = CI.getSourceManager();
            auto &AST = CI.getASTContext();

            auto inFile = getCurrentFile().str();
            const auto &fileData = m_fileDataMap[inFile];
            bool fileNeedsPatch = false;

            for (const auto &E : fileData.callbackInvokeExprList) {
                auto T = realCalleeType(E, AST);
                auto typeStr = getTypeString(T);
                if (!g_ctx().requestedSignatures.count(typeStr)) {
                    continue;
                }
                g_ctx().sourceStat.callbackCheckGuardSignatures.insert(typeStr);
                fileNeedsPatch = true;
            }

            for (const auto &E : fileData.functionDecayExprList) {
                auto FD = E->getDecl()->getAsFunction();
                auto T = AST.getPointerType(FD->getType());
                auto typeStr = getTypeString(T);
                if (!g_ctx().requestedSignatures.count(typeStr)) {
                    continue;
                }
                assert(FD);
                g_ctx().sourceStat.functionDecayGuardStats[typeStr].locations.insert(
                    std::make_pair(FD->getBeginLoc().printToString(SM), inFile));
                fileNeedsPatch = true;
            }

            if (fileNeedsPatch) {
                g_ctx().sourceStat.filesNeedPatch.insert(inFile);
            }
        }

        std::unique_ptr<ASTConsumer> CreateASTConsumer(CompilerInstance &CI,
                                                       StringRef InFile) override {
            auto &fileData = m_fileDataMap[InFile.str()];
            return std::make_unique<HLR::FunctionExprConsumer>(fileData.callbackInvokeExprList,
                                                               fileData.functionDecayExprList);
        }

    private:
        struct ConsumedFileData {
            llvm::SmallVector<const CallExpr *, 20> callbackInvokeExprList;
            llvm::SmallVector<const DeclRefExpr *, 20> functionDecayExprList;
        };
        std::map<std::string, ConsumedFileData> m_fileDataMap;
    };

    const char *name = "stat";

    const char *help = "Probe statistics of input files";

    int main(int argc, char *argv[]) {
        static cl::OptionCategory myOptionCat("Lorelei Host Library Rewriter - Statistics");
        static cl::opt<std::string> statOption("s", cl::desc("Specify TLC stat JSON"),
                                               cl::value_desc("stat json"), cl::cat(myOptionCat),
                                               cl::Required);
        static cl::opt<std::string> outputOption("o", cl::desc("Specify output file"),
                                                 cl::value_desc("output file"),
                                                 cl::cat(myOptionCat));
        static cl::extrahelp commonHelp(CommonOptionsParser::HelpMessage);

        auto expectedParser =
            CommonOptionsParser::create(argc, const_cast<const char **>(argv), myOptionCat);
        if (!expectedParser) {
            llvm::errs() << expectedParser.takeError();
            return 0;
        }
        auto &parser = expectedParser.get();

        if (std::error_code ec; (ec = llvm::sys::fs::current_path(g_ctx().initialCwd))) {
            llvm::errs() << "Failed to get current path: " << ec.message() << "\n";
            return 1;
        }
        g_ctx().manifestStatPath = statOption.getValue();
        g_ctx().outputPath = outputOption.getValue();

        /// STEP: Read manifest stat file generated by TLC `stat`
        {
            TLC::ManifestStatistics manifestStat;
            if (std::string err; !manifestStat.loadFromJson(g_ctx().manifestStatPath, err)) {
                llvm::errs() << "Failed to parse manifest stat file: " << err << "\n";
                return 1;
            }
            for (const auto &pair : manifestStat.callbacks) {
                g_ctx().requestedSignatures.insert(pair.first);
            }
        }

        ClangTool tool(parser.getCompilations(), parser.getSourcePathList());
        if (int ret = tool.run(newFrontendActionFactory<MyASTFrontendAction>().get()); ret == 1) {
            return ret;
        }

        if (std::string err; !g_ctx().sourceStat.saveAsJson(
                g_ctx().outputPath.empty() ? "-" : g_ctx().outputPath, err)) {
            llvm::errs() << "Error occurs opening output file: " << err << "\n";
            return 1;
        }
        return 0;
    }

}
