#define LORETHUNK_VULKAN_API_FOREACH(F)                                                            \
    F(vkCreateInstance)                                                                            \
    F(vkDestroyInstance)                                                                           \
    F(vkEnumeratePhysicalDevices)                                                                  \
    F(vkGetPhysicalDeviceFeatures)                                                                 \
    F(vkGetPhysicalDeviceFormatProperties)                                                         \
    F(vkGetPhysicalDeviceImageFormatProperties)                                                    \
    F(vkGetPhysicalDeviceProperties)                                                               \
    F(vkGetPhysicalDeviceQueueFamilyProperties)                                                    \
    F(vkGetPhysicalDeviceMemoryProperties)                                                         \
    F(vkGetInstanceProcAddr)                                                                       \
    F(vkGetDeviceProcAddr)                                                                         \
    F(vkCreateDevice)                                                                              \
    F(vkDestroyDevice)                                                                             \
    F(vkEnumerateInstanceExtensionProperties)                                                      \
    F(vkEnumerateDeviceExtensionProperties)                                                        \
    F(vkEnumerateInstanceLayerProperties)                                                          \
    F(vkEnumerateDeviceLayerProperties)                                                            \
    F(vkGetDeviceQueue)                                                                            \
    F(vkQueueSubmit)                                                                               \
    F(vkQueueWaitIdle)                                                                             \
    F(vkDeviceWaitIdle)                                                                            \
    F(vkAllocateMemory)                                                                            \
    F(vkFreeMemory)                                                                                \
    F(vkMapMemory)                                                                                 \
    F(vkUnmapMemory)                                                                               \
    F(vkFlushMappedMemoryRanges)                                                                   \
    F(vkInvalidateMappedMemoryRanges)                                                              \
    F(vkGetDeviceMemoryCommitment)                                                                 \
    F(vkBindBufferMemory)                                                                          \
    F(vkBindImageMemory)                                                                           \
    F(vkGetBufferMemoryRequirements)                                                               \
    F(vkGetImageMemoryRequirements)                                                                \
    F(vkGetImageSparseMemoryRequirements)                                                          \
    F(vkGetPhysicalDeviceSparseImageFormatProperties)                                              \
    F(vkQueueBindSparse)                                                                           \
    F(vkCreateFence)                                                                               \
    F(vkDestroyFence)                                                                              \
    F(vkResetFences)                                                                               \
    F(vkGetFenceStatus)                                                                            \
    F(vkWaitForFences)                                                                             \
    F(vkCreateSemaphore)                                                                           \
    F(vkDestroySemaphore)                                                                          \
    F(vkCreateEvent)                                                                               \
    F(vkDestroyEvent)                                                                              \
    F(vkGetEventStatus)                                                                            \
    F(vkSetEvent)                                                                                  \
    F(vkResetEvent)                                                                                \
    F(vkCreateQueryPool)                                                                           \
    F(vkDestroyQueryPool)                                                                          \
    F(vkGetQueryPoolResults)                                                                       \
    F(vkCreateBuffer)                                                                              \
    F(vkDestroyBuffer)                                                                             \
    F(vkCreateBufferView)                                                                          \
    F(vkDestroyBufferView)                                                                         \
    F(vkCreateImage)                                                                               \
    F(vkDestroyImage)                                                                              \
    F(vkGetImageSubresourceLayout)                                                                 \
    F(vkCreateImageView)                                                                           \
    F(vkDestroyImageView)                                                                          \
    F(vkCreateShaderModule)                                                                        \
    F(vkDestroyShaderModule)                                                                       \
    F(vkCreatePipelineCache)                                                                       \
    F(vkDestroyPipelineCache)                                                                      \
    F(vkGetPipelineCacheData)                                                                      \
    F(vkMergePipelineCaches)                                                                       \
    F(vkCreateGraphicsPipelines)                                                                   \
    F(vkCreateComputePipelines)                                                                    \
    F(vkDestroyPipeline)                                                                           \
    F(vkCreatePipelineLayout)                                                                      \
    F(vkDestroyPipelineLayout)                                                                     \
    F(vkCreateSampler)                                                                             \
    F(vkDestroySampler)                                                                            \
    F(vkCreateDescriptorSetLayout)                                                                 \
    F(vkDestroyDescriptorSetLayout)                                                                \
    F(vkCreateDescriptorPool)                                                                      \
    F(vkDestroyDescriptorPool)                                                                     \
    F(vkResetDescriptorPool)                                                                       \
    F(vkAllocateDescriptorSets)                                                                    \
    F(vkFreeDescriptorSets)                                                                        \
    F(vkUpdateDescriptorSets)                                                                      \
    F(vkCreateFramebuffer)                                                                         \
    F(vkDestroyFramebuffer)                                                                        \
    F(vkCreateRenderPass)                                                                          \
    F(vkDestroyRenderPass)                                                                         \
    F(vkGetRenderAreaGranularity)                                                                  \
    F(vkCreateCommandPool)                                                                         \
    F(vkDestroyCommandPool)                                                                        \
    F(vkResetCommandPool)                                                                          \
    F(vkAllocateCommandBuffers)                                                                    \
    F(vkFreeCommandBuffers)                                                                        \
    F(vkBeginCommandBuffer)                                                                        \
    F(vkEndCommandBuffer)                                                                          \
    F(vkResetCommandBuffer)                                                                        \
    F(vkCmdBindPipeline)                                                                           \
    F(vkCmdSetViewport)                                                                            \
    F(vkCmdSetScissor)                                                                             \
    F(vkCmdSetLineWidth)                                                                           \
    F(vkCmdSetDepthBias)                                                                           \
    F(vkCmdSetBlendConstants)                                                                      \
    F(vkCmdSetDepthBounds)                                                                         \
    F(vkCmdSetStencilCompareMask)                                                                  \
    F(vkCmdSetStencilWriteMask)                                                                    \
    F(vkCmdSetStencilReference)                                                                    \
    F(vkCmdBindDescriptorSets)                                                                     \
    F(vkCmdBindIndexBuffer)                                                                        \
    F(vkCmdBindVertexBuffers)                                                                      \
    F(vkCmdDraw)                                                                                   \
    F(vkCmdDrawIndexed)                                                                            \
    F(vkCmdDrawIndirect)                                                                           \
    F(vkCmdDrawIndexedIndirect)                                                                    \
    F(vkCmdDispatch)                                                                               \
    F(vkCmdDispatchIndirect)                                                                       \
    F(vkCmdCopyBuffer)                                                                             \
    F(vkCmdCopyImage)                                                                              \
    F(vkCmdBlitImage)                                                                              \
    F(vkCmdCopyBufferToImage)                                                                      \
    F(vkCmdCopyImageToBuffer)                                                                      \
    F(vkCmdUpdateBuffer)                                                                           \
    F(vkCmdFillBuffer)                                                                             \
    F(vkCmdClearColorImage)                                                                        \
    F(vkCmdClearDepthStencilImage)                                                                 \
    F(vkCmdClearAttachments)                                                                       \
    F(vkCmdResolveImage)                                                                           \
    F(vkCmdSetEvent)                                                                               \
    F(vkCmdResetEvent)                                                                             \
    F(vkCmdWaitEvents)                                                                             \
    F(vkCmdPipelineBarrier)                                                                        \
    F(vkCmdBeginQuery)                                                                             \
    F(vkCmdEndQuery)                                                                               \
    F(vkCmdResetQueryPool)                                                                         \
    F(vkCmdWriteTimestamp)                                                                         \
    F(vkCmdCopyQueryPoolResults)                                                                   \
    F(vkCmdPushConstants)                                                                          \
    F(vkCmdBeginRenderPass)                                                                        \
    F(vkCmdNextSubpass)                                                                            \
    F(vkCmdEndRenderPass)                                                                          \
    F(vkCmdExecuteCommands)                                                                        \
    F(vkEnumerateInstanceVersion)                                                                  \
    F(vkBindBufferMemory2)                                                                         \
    F(vkBindImageMemory2)                                                                          \
    F(vkGetDeviceGroupPeerMemoryFeatures)                                                          \
    F(vkCmdSetDeviceMask)                                                                          \
    F(vkCmdDispatchBase)                                                                           \
    F(vkEnumeratePhysicalDeviceGroups)                                                             \
    F(vkGetImageMemoryRequirements2)                                                               \
    F(vkGetBufferMemoryRequirements2)                                                              \
    F(vkGetImageSparseMemoryRequirements2)                                                         \
    F(vkGetPhysicalDeviceFeatures2)                                                                \
    F(vkGetPhysicalDeviceProperties2)                                                              \
    F(vkGetPhysicalDeviceFormatProperties2)                                                        \
    F(vkGetPhysicalDeviceImageFormatProperties2)                                                   \
    F(vkGetPhysicalDeviceQueueFamilyProperties2)                                                   \
    F(vkGetPhysicalDeviceMemoryProperties2)                                                        \
    F(vkGetPhysicalDeviceSparseImageFormatProperties2)                                             \
    F(vkTrimCommandPool)                                                                           \
    F(vkGetDeviceQueue2)                                                                           \
    F(vkCreateSamplerYcbcrConversion)                                                              \
    F(vkDestroySamplerYcbcrConversion)                                                             \
    F(vkCreateDescriptorUpdateTemplate)                                                            \
    F(vkDestroyDescriptorUpdateTemplate)                                                           \
    F(vkUpdateDescriptorSetWithTemplate)                                                           \
    F(vkGetPhysicalDeviceExternalBufferProperties)                                                 \
    F(vkGetPhysicalDeviceExternalFenceProperties)                                                  \
    F(vkGetPhysicalDeviceExternalSemaphoreProperties)                                              \
    F(vkGetDescriptorSetLayoutSupport)                                                             \
    F(vkCmdDrawIndirectCount)                                                                      \
    F(vkCmdDrawIndexedIndirectCount)                                                               \
    F(vkCreateRenderPass2)                                                                         \
    F(vkCmdBeginRenderPass2)                                                                       \
    F(vkCmdNextSubpass2)                                                                           \
    F(vkCmdEndRenderPass2)                                                                         \
    F(vkResetQueryPool)                                                                            \
    F(vkGetSemaphoreCounterValue)                                                                  \
    F(vkWaitSemaphores)                                                                            \
    F(vkSignalSemaphore)                                                                           \
    F(vkGetBufferDeviceAddress)                                                                    \
    F(vkGetBufferOpaqueCaptureAddress)                                                             \
    F(vkGetDeviceMemoryOpaqueCaptureAddress)                                                       \
    F(vkGetPhysicalDeviceToolProperties)                                                           \
    F(vkCreatePrivateDataSlot)                                                                     \
    F(vkDestroyPrivateDataSlot)                                                                    \
    F(vkSetPrivateData)                                                                            \
    F(vkGetPrivateData)                                                                            \
    F(vkCmdSetEvent2)                                                                              \
    F(vkCmdResetEvent2)                                                                            \
    F(vkCmdWaitEvents2)                                                                            \
    F(vkCmdPipelineBarrier2)                                                                       \
    F(vkCmdWriteTimestamp2)                                                                        \
    F(vkQueueSubmit2)                                                                              \
    F(vkCmdCopyBuffer2)                                                                            \
    F(vkCmdCopyImage2)                                                                             \
    F(vkCmdCopyBufferToImage2)                                                                     \
    F(vkCmdCopyImageToBuffer2)                                                                     \
    F(vkCmdBlitImage2)                                                                             \
    F(vkCmdResolveImage2)                                                                          \
    F(vkCmdBeginRendering)                                                                         \
    F(vkCmdEndRendering)                                                                           \
    F(vkCmdSetCullMode)                                                                            \
    F(vkCmdSetFrontFace)                                                                           \
    F(vkCmdSetPrimitiveTopology)                                                                   \
    F(vkCmdSetViewportWithCount)                                                                   \
    F(vkCmdSetScissorWithCount)                                                                    \
    F(vkCmdBindVertexBuffers2)                                                                     \
    F(vkCmdSetDepthTestEnable)                                                                     \
    F(vkCmdSetDepthWriteEnable)                                                                    \
    F(vkCmdSetDepthCompareOp)                                                                      \
    F(vkCmdSetDepthBoundsTestEnable)                                                               \
    F(vkCmdSetStencilTestEnable)                                                                   \
    F(vkCmdSetStencilOp)                                                                           \
    F(vkCmdSetRasterizerDiscardEnable)                                                             \
    F(vkCmdSetDepthBiasEnable)                                                                     \
    F(vkCmdSetPrimitiveRestartEnable)                                                              \
    F(vkGetDeviceBufferMemoryRequirements)                                                         \
    F(vkGetDeviceImageMemoryRequirements)                                                          \
    F(vkGetDeviceImageSparseMemoryRequirements)                                                    \
    F(vkCmdSetLineStipple)                                                                         \
    F(vkMapMemory2)                                                                                \
    F(vkUnmapMemory2)                                                                              \
    F(vkCmdBindIndexBuffer2)                                                                       \
    F(vkGetRenderingAreaGranularity)                                                               \
    F(vkGetDeviceImageSubresourceLayout)                                                           \
    F(vkGetImageSubresourceLayout2)                                                                \
    F(vkCmdPushDescriptorSet)                                                                      \
    F(vkCmdPushDescriptorSetWithTemplate)                                                          \
    F(vkCmdSetRenderingAttachmentLocations)                                                        \
    F(vkCmdSetRenderingInputAttachmentIndices)                                                     \
    F(vkCmdBindDescriptorSets2)                                                                    \
    F(vkCmdPushConstants2)                                                                         \
    F(vkCmdPushDescriptorSet2)                                                                     \
    F(vkCmdPushDescriptorSetWithTemplate2)                                                         \
    F(vkCopyMemoryToImage)                                                                         \
    F(vkCopyImageToMemory)                                                                         \
    F(vkCopyImageToImage)                                                                          \
    F(vkTransitionImageLayout)                                                                     \
    F(vkDestroySurfaceKHR)                                                                         \
    F(vkGetPhysicalDeviceSurfaceSupportKHR)                                                        \
    F(vkGetPhysicalDeviceSurfaceCapabilitiesKHR)                                                   \
    F(vkGetPhysicalDeviceSurfaceFormatsKHR)                                                        \
    F(vkGetPhysicalDeviceSurfacePresentModesKHR)                                                   \
    F(vkCreateSwapchainKHR)                                                                        \
    F(vkDestroySwapchainKHR)                                                                       \
    F(vkGetSwapchainImagesKHR)                                                                     \
    F(vkAcquireNextImageKHR)                                                                       \
    F(vkQueuePresentKHR)                                                                           \
    F(vkGetDeviceGroupPresentCapabilitiesKHR)                                                      \
    F(vkGetDeviceGroupSurfacePresentModesKHR)                                                      \
    F(vkGetPhysicalDevicePresentRectanglesKHR)                                                     \
    F(vkAcquireNextImage2KHR)                                                                      \
    F(vkGetPhysicalDeviceDisplayPropertiesKHR)                                                     \
    F(vkGetPhysicalDeviceDisplayPlanePropertiesKHR)                                                \
    F(vkGetDisplayPlaneSupportedDisplaysKHR)                                                       \
    F(vkGetDisplayModePropertiesKHR)                                                               \
    F(vkCreateDisplayModeKHR)                                                                      \
    F(vkGetDisplayPlaneCapabilitiesKHR)                                                            \
    F(vkCreateDisplayPlaneSurfaceKHR)                                                              \
    F(vkCreateSharedSwapchainsKHR)                                                                 \
    F(vkGetPhysicalDeviceVideoCapabilitiesKHR)                                                     \
    F(vkGetPhysicalDeviceVideoFormatPropertiesKHR)                                                 \
    F(vkCreateVideoSessionKHR)                                                                     \
    F(vkDestroyVideoSessionKHR)                                                                    \
    F(vkGetVideoSessionMemoryRequirementsKHR)                                                      \
    F(vkBindVideoSessionMemoryKHR)                                                                 \
    F(vkCreateVideoSessionParametersKHR)                                                           \
    F(vkUpdateVideoSessionParametersKHR)                                                           \
    F(vkDestroyVideoSessionParametersKHR)                                                          \
    F(vkCmdBeginVideoCodingKHR)                                                                    \
    F(vkCmdEndVideoCodingKHR)                                                                      \
    F(vkCmdControlVideoCodingKHR)                                                                  \
    F(vkCmdDecodeVideoKHR)                                                                         \
    F(vkCmdBeginRenderingKHR)                                                                      \
    F(vkCmdEndRenderingKHR)                                                                        \
    F(vkGetPhysicalDeviceFeatures2KHR)                                                             \
    F(vkGetPhysicalDeviceProperties2KHR)                                                           \
    F(vkGetPhysicalDeviceFormatProperties2KHR)                                                     \
    F(vkGetPhysicalDeviceImageFormatProperties2KHR)                                                \
    F(vkGetPhysicalDeviceQueueFamilyProperties2KHR)                                                \
    F(vkGetPhysicalDeviceMemoryProperties2KHR)                                                     \
    F(vkGetPhysicalDeviceSparseImageFormatProperties2KHR)                                          \
    F(vkGetDeviceGroupPeerMemoryFeaturesKHR)                                                       \
    F(vkCmdSetDeviceMaskKHR)                                                                       \
    F(vkCmdDispatchBaseKHR)                                                                        \
    F(vkTrimCommandPoolKHR)                                                                        \
    F(vkEnumeratePhysicalDeviceGroupsKHR)                                                          \
    F(vkGetPhysicalDeviceExternalBufferPropertiesKHR)                                              \
    F(vkGetMemoryFdKHR)                                                                            \
    F(vkGetMemoryFdPropertiesKHR)                                                                  \
    F(vkGetPhysicalDeviceExternalSemaphorePropertiesKHR)                                           \
    F(vkImportSemaphoreFdKHR)                                                                      \
    F(vkGetSemaphoreFdKHR)                                                                         \
    F(vkCmdPushDescriptorSetKHR)                                                                   \
    F(vkCmdPushDescriptorSetWithTemplateKHR)                                                       \
    F(vkCreateDescriptorUpdateTemplateKHR)                                                         \
    F(vkDestroyDescriptorUpdateTemplateKHR)                                                        \
    F(vkUpdateDescriptorSetWithTemplateKHR)                                                        \
    F(vkCreateRenderPass2KHR)                                                                      \
    F(vkCmdBeginRenderPass2KHR)                                                                    \
    F(vkCmdNextSubpass2KHR)                                                                        \
    F(vkCmdEndRenderPass2KHR)                                                                      \
    F(vkGetSwapchainStatusKHR)                                                                     \
    F(vkGetPhysicalDeviceExternalFencePropertiesKHR)                                               \
    F(vkImportFenceFdKHR)                                                                          \
    F(vkGetFenceFdKHR)                                                                             \
    F(vkEnumeratePhysicalDeviceQueueFamilyPerformanceQueryCountersKHR)                             \
    F(vkGetPhysicalDeviceQueueFamilyPerformanceQueryPassesKHR)                                     \
    F(vkAcquireProfilingLockKHR)                                                                   \
    F(vkReleaseProfilingLockKHR)                                                                   \
    F(vkGetPhysicalDeviceSurfaceCapabilities2KHR)                                                  \
    F(vkGetPhysicalDeviceSurfaceFormats2KHR)                                                       \
    F(vkGetPhysicalDeviceDisplayProperties2KHR)                                                    \
    F(vkGetPhysicalDeviceDisplayPlaneProperties2KHR)                                               \
    F(vkGetDisplayModeProperties2KHR)                                                              \
    F(vkGetDisplayPlaneCapabilities2KHR)                                                           \
    F(vkGetImageMemoryRequirements2KHR)                                                            \
    F(vkGetBufferMemoryRequirements2KHR)                                                           \
    F(vkGetImageSparseMemoryRequirements2KHR)                                                      \
    F(vkCreateSamplerYcbcrConversionKHR)                                                           \
    F(vkDestroySamplerYcbcrConversionKHR)                                                          \
    F(vkBindBufferMemory2KHR)                                                                      \
    F(vkBindImageMemory2KHR)                                                                       \
    F(vkGetDescriptorSetLayoutSupportKHR)                                                          \
    F(vkCmdDrawIndirectCountKHR)                                                                   \
    F(vkCmdDrawIndexedIndirectCountKHR)                                                            \
    F(vkGetSemaphoreCounterValueKHR)                                                               \
    F(vkWaitSemaphoresKHR)                                                                         \
    F(vkSignalSemaphoreKHR)                                                                        \
    F(vkGetPhysicalDeviceFragmentShadingRatesKHR)                                                  \
    F(vkCmdSetFragmentShadingRateKHR)                                                              \
    F(vkCmdSetRenderingAttachmentLocationsKHR)                                                     \
    F(vkCmdSetRenderingInputAttachmentIndicesKHR)                                                  \
    F(vkWaitForPresentKHR)                                                                         \
    F(vkGetBufferDeviceAddressKHR)                                                                 \
    F(vkGetBufferOpaqueCaptureAddressKHR)                                                          \
    F(vkGetDeviceMemoryOpaqueCaptureAddressKHR)                                                    \
    F(vkCreateDeferredOperationKHR)                                                                \
    F(vkDestroyDeferredOperationKHR)                                                               \
    F(vkGetDeferredOperationMaxConcurrencyKHR)                                                     \
    F(vkGetDeferredOperationResultKHR)                                                             \
    F(vkDeferredOperationJoinKHR)                                                                  \
    F(vkGetPipelineExecutablePropertiesKHR)                                                        \
    F(vkGetPipelineExecutableStatisticsKHR)                                                        \
    F(vkGetPipelineExecutableInternalRepresentationsKHR)                                           \
    F(vkMapMemory2KHR)                                                                             \
    F(vkUnmapMemory2KHR)                                                                           \
    F(vkGetPhysicalDeviceVideoEncodeQualityLevelPropertiesKHR)                                     \
    F(vkGetEncodedVideoSessionParametersKHR)                                                       \
    F(vkCmdEncodeVideoKHR)                                                                         \
    F(vkCmdSetEvent2KHR)                                                                           \
    F(vkCmdResetEvent2KHR)                                                                         \
    F(vkCmdWaitEvents2KHR)                                                                         \
    F(vkCmdPipelineBarrier2KHR)                                                                    \
    F(vkCmdWriteTimestamp2KHR)                                                                     \
    F(vkQueueSubmit2KHR)                                                                           \
    F(vkCmdCopyBuffer2KHR)                                                                         \
    F(vkCmdCopyImage2KHR)                                                                          \
    F(vkCmdCopyBufferToImage2KHR)                                                                  \
    F(vkCmdCopyImageToBuffer2KHR)                                                                  \
    F(vkCmdBlitImage2KHR)                                                                          \
    F(vkCmdResolveImage2KHR)                                                                       \
    F(vkCmdTraceRaysIndirect2KHR)                                                                  \
    F(vkGetDeviceBufferMemoryRequirementsKHR)                                                      \
    F(vkGetDeviceImageMemoryRequirementsKHR)                                                       \
    F(vkGetDeviceImageSparseMemoryRequirementsKHR)                                                 \
    F(vkCmdBindIndexBuffer2KHR)                                                                    \
    F(vkGetRenderingAreaGranularityKHR)                                                            \
    F(vkGetDeviceImageSubresourceLayoutKHR)                                                        \
    F(vkGetImageSubresourceLayout2KHR)                                                             \
    F(vkWaitForPresent2KHR)                                                                        \
    F(vkCreatePipelineBinariesKHR)                                                                 \
    F(vkDestroyPipelineBinaryKHR)                                                                  \
    F(vkGetPipelineKeyKHR)                                                                         \
    F(vkGetPipelineBinaryDataKHR)                                                                  \
    F(vkReleaseCapturedPipelineDataKHR)                                                            \
    F(vkReleaseSwapchainImagesKHR)                                                                 \
    F(vkGetPhysicalDeviceCooperativeMatrixPropertiesKHR)                                           \
    F(vkCmdSetLineStippleKHR)                                                                      \
    F(vkGetPhysicalDeviceCalibrateableTimeDomainsKHR)                                              \
    F(vkGetCalibratedTimestampsKHR)                                                                \
    F(vkCmdBindDescriptorSets2KHR)                                                                 \
    F(vkCmdPushConstants2KHR)                                                                      \
    F(vkCmdPushDescriptorSet2KHR)                                                                  \
    F(vkCmdPushDescriptorSetWithTemplate2KHR)                                                      \
    F(vkCmdSetDescriptorBufferOffsets2EXT)                                                         \
    F(vkCmdBindDescriptorBufferEmbeddedSamplers2EXT)                                               \
    F(vkCreateDebugReportCallbackEXT)                                                              \
    F(vkDestroyDebugReportCallbackEXT)                                                             \
    F(vkDebugReportMessageEXT)                                                                     \
    F(vkDebugMarkerSetObjectTagEXT)                                                                \
    F(vkDebugMarkerSetObjectNameEXT)                                                               \
    F(vkCmdDebugMarkerBeginEXT)                                                                    \
    F(vkCmdDebugMarkerEndEXT)                                                                      \
    F(vkCmdDebugMarkerInsertEXT)                                                                   \
    F(vkCmdBindTransformFeedbackBuffersEXT)                                                        \
    F(vkCmdBeginTransformFeedbackEXT)                                                              \
    F(vkCmdEndTransformFeedbackEXT)                                                                \
    F(vkCmdBeginQueryIndexedEXT)                                                                   \
    F(vkCmdEndQueryIndexedEXT)                                                                     \
    F(vkCmdDrawIndirectByteCountEXT)                                                               \
    F(vkCreateCuModuleNVX)                                                                         \
    F(vkCreateCuFunctionNVX)                                                                       \
    F(vkDestroyCuModuleNVX)                                                                        \
    F(vkDestroyCuFunctionNVX)                                                                      \
    F(vkCmdCuLaunchKernelNVX)                                                                      \
    F(vkGetImageViewHandleNVX)                                                                     \
    F(vkGetImageViewHandle64NVX)                                                                   \
    F(vkGetImageViewAddressNVX)                                                                    \
    F(vkCmdDrawIndirectCountAMD)                                                                   \
    F(vkCmdDrawIndexedIndirectCountAMD)                                                            \
    F(vkGetShaderInfoAMD)                                                                          \
    F(vkGetPhysicalDeviceExternalImageFormatPropertiesNV)                                          \
    F(vkCmdBeginConditionalRenderingEXT)                                                           \
    F(vkCmdEndConditionalRenderingEXT)                                                             \
    F(vkCmdSetViewportWScalingNV)                                                                  \
    F(vkReleaseDisplayEXT)                                                                         \
    F(vkGetPhysicalDeviceSurfaceCapabilities2EXT)                                                  \
    F(vkDisplayPowerControlEXT)                                                                    \
    F(vkRegisterDeviceEventEXT)                                                                    \
    F(vkRegisterDisplayEventEXT)                                                                   \
    F(vkGetSwapchainCounterEXT)                                                                    \
    F(vkGetRefreshCycleDurationGOOGLE)                                                             \
    F(vkGetPastPresentationTimingGOOGLE)                                                           \
    F(vkCmdSetDiscardRectangleEXT)                                                                 \
    F(vkCmdSetDiscardRectangleEnableEXT)                                                           \
    F(vkCmdSetDiscardRectangleModeEXT)                                                             \
    F(vkSetHdrMetadataEXT)                                                                         \
    F(vkSetDebugUtilsObjectNameEXT)                                                                \
    F(vkSetDebugUtilsObjectTagEXT)                                                                 \
    F(vkQueueBeginDebugUtilsLabelEXT)                                                              \
    F(vkQueueEndDebugUtilsLabelEXT)                                                                \
    F(vkQueueInsertDebugUtilsLabelEXT)                                                             \
    F(vkCmdBeginDebugUtilsLabelEXT)                                                                \
    F(vkCmdEndDebugUtilsLabelEXT)                                                                  \
    F(vkCmdInsertDebugUtilsLabelEXT)                                                               \
    F(vkCreateDebugUtilsMessengerEXT)                                                              \
    F(vkDestroyDebugUtilsMessengerEXT)                                                             \
    F(vkSubmitDebugUtilsMessageEXT)                                                                \
    F(vkCmdSetSampleLocationsEXT)                                                                  \
    F(vkGetPhysicalDeviceMultisamplePropertiesEXT)                                                 \
    F(vkGetImageDrmFormatModifierPropertiesEXT)                                                    \
    F(vkCreateValidationCacheEXT)                                                                  \
    F(vkDestroyValidationCacheEXT)                                                                 \
    F(vkMergeValidationCachesEXT)                                                                  \
    F(vkGetValidationCacheDataEXT)                                                                 \
    F(vkCmdBindShadingRateImageNV)                                                                 \
    F(vkCmdSetViewportShadingRatePaletteNV)                                                        \
    F(vkCmdSetCoarseSampleOrderNV)                                                                 \
    F(vkCreateAccelerationStructureNV)                                                             \
    F(vkDestroyAccelerationStructureNV)                                                            \
    F(vkGetAccelerationStructureMemoryRequirementsNV)                                              \
    F(vkBindAccelerationStructureMemoryNV)                                                         \
    F(vkCmdBuildAccelerationStructureNV)                                                           \
    F(vkCmdCopyAccelerationStructureNV)                                                            \
    F(vkCmdTraceRaysNV)                                                                            \
    F(vkCreateRayTracingPipelinesNV)                                                               \
    F(vkGetRayTracingShaderGroupHandlesKHR)                                                        \
    F(vkGetRayTracingShaderGroupHandlesNV)                                                         \
    F(vkGetAccelerationStructureHandleNV)                                                          \
    F(vkCmdWriteAccelerationStructuresPropertiesNV)                                                \
    F(vkCompileDeferredNV)                                                                         \
    F(vkGetMemoryHostPointerPropertiesEXT)                                                         \
    F(vkCmdWriteBufferMarkerAMD)                                                                   \
    F(vkCmdWriteBufferMarker2AMD)                                                                  \
    F(vkGetPhysicalDeviceCalibrateableTimeDomainsEXT)                                              \
    F(vkGetCalibratedTimestampsEXT)                                                                \
    F(vkCmdDrawMeshTasksNV)                                                                        \
    F(vkCmdDrawMeshTasksIndirectNV)                                                                \
    F(vkCmdDrawMeshTasksIndirectCountNV)                                                           \
    F(vkCmdSetExclusiveScissorEnableNV)                                                            \
    F(vkCmdSetExclusiveScissorNV)                                                                  \
    F(vkCmdSetCheckpointNV)                                                                        \
    F(vkGetQueueCheckpointDataNV)                                                                  \
    F(vkGetQueueCheckpointData2NV)                                                                 \
    F(vkInitializePerformanceApiINTEL)                                                             \
    F(vkUninitializePerformanceApiINTEL)                                                           \
    F(vkCmdSetPerformanceMarkerINTEL)                                                              \
    F(vkCmdSetPerformanceStreamMarkerINTEL)                                                        \
    F(vkCmdSetPerformanceOverrideINTEL)                                                            \
    F(vkAcquirePerformanceConfigurationINTEL)                                                      \
    F(vkReleasePerformanceConfigurationINTEL)                                                      \
    F(vkQueueSetPerformanceConfigurationINTEL)                                                     \
    F(vkGetPerformanceParameterINTEL)                                                              \
    F(vkSetLocalDimmingAMD)                                                                        \
    F(vkGetBufferDeviceAddressEXT)                                                                 \
    F(vkGetPhysicalDeviceToolPropertiesEXT)                                                        \
    F(vkGetPhysicalDeviceCooperativeMatrixPropertiesNV)                                            \
    F(vkGetPhysicalDeviceSupportedFramebufferMixedSamplesCombinationsNV)                           \
    F(vkCreateHeadlessSurfaceEXT)                                                                  \
    F(vkCmdSetLineStippleEXT)                                                                      \
    F(vkResetQueryPoolEXT)                                                                         \
    F(vkCmdSetCullModeEXT)                                                                         \
    F(vkCmdSetFrontFaceEXT)                                                                        \
    F(vkCmdSetPrimitiveTopologyEXT)                                                                \
    F(vkCmdSetViewportWithCountEXT)                                                                \
    F(vkCmdSetScissorWithCountEXT)                                                                 \
    F(vkCmdBindVertexBuffers2EXT)                                                                  \
    F(vkCmdSetDepthTestEnableEXT)                                                                  \
    F(vkCmdSetDepthWriteEnableEXT)                                                                 \
    F(vkCmdSetDepthCompareOpEXT)                                                                   \
    F(vkCmdSetDepthBoundsTestEnableEXT)                                                            \
    F(vkCmdSetStencilTestEnableEXT)                                                                \
    F(vkCmdSetStencilOpEXT)                                                                        \
    F(vkCopyMemoryToImageEXT)                                                                      \
    F(vkCopyImageToMemoryEXT)                                                                      \
    F(vkCopyImageToImageEXT)                                                                       \
    F(vkTransitionImageLayoutEXT)                                                                  \
    F(vkGetImageSubresourceLayout2EXT)                                                             \
    F(vkReleaseSwapchainImagesEXT)                                                                 \
    F(vkGetGeneratedCommandsMemoryRequirementsNV)                                                  \
    F(vkCmdPreprocessGeneratedCommandsNV)                                                          \
    F(vkCmdExecuteGeneratedCommandsNV)                                                             \
    F(vkCmdBindPipelineShaderGroupNV)                                                              \
    F(vkCreateIndirectCommandsLayoutNV)                                                            \
    F(vkDestroyIndirectCommandsLayoutNV)                                                           \
    F(vkCmdSetDepthBias2EXT)                                                                       \
    F(vkAcquireDrmDisplayEXT)                                                                      \
    F(vkGetDrmDisplayEXT)                                                                          \
    F(vkCreatePrivateDataSlotEXT)                                                                  \
    F(vkDestroyPrivateDataSlotEXT)                                                                 \
    F(vkSetPrivateDataEXT)                                                                         \
    F(vkGetPrivateDataEXT)                                                                         \
    F(vkCmdDispatchTileQCOM)                                                                       \
    F(vkCmdBeginPerTileExecutionQCOM)                                                              \
    F(vkCmdEndPerTileExecutionQCOM)                                                                \
    F(vkGetDescriptorSetLayoutSizeEXT)                                                             \
    F(vkGetDescriptorSetLayoutBindingOffsetEXT)                                                    \
    F(vkGetDescriptorEXT)                                                                          \
    F(vkCmdBindDescriptorBuffersEXT)                                                               \
    F(vkCmdSetDescriptorBufferOffsetsEXT)                                                          \
    F(vkCmdBindDescriptorBufferEmbeddedSamplersEXT)                                                \
    F(vkGetBufferOpaqueCaptureDescriptorDataEXT)                                                   \
    F(vkGetImageOpaqueCaptureDescriptorDataEXT)                                                    \
    F(vkGetImageViewOpaqueCaptureDescriptorDataEXT)                                                \
    F(vkGetSamplerOpaqueCaptureDescriptorDataEXT)                                                  \
    F(vkGetAccelerationStructureOpaqueCaptureDescriptorDataEXT)                                    \
    F(vkCmdSetFragmentShadingRateEnumNV)                                                           \
    F(vkGetDeviceFaultInfoEXT)                                                                     \
    F(vkCmdSetVertexInputEXT)                                                                      \
    F(vkGetDeviceSubpassShadingMaxWorkgroupSizeHUAWEI)                                             \
    F(vkCmdSubpassShadingHUAWEI)                                                                   \
    F(vkCmdBindInvocationMaskHUAWEI)                                                               \
    F(vkGetMemoryRemoteAddressNV)                                                                  \
    F(vkGetPipelinePropertiesEXT)                                                                  \
    F(vkCmdSetPatchControlPointsEXT)                                                               \
    F(vkCmdSetRasterizerDiscardEnableEXT)                                                          \
    F(vkCmdSetDepthBiasEnableEXT)                                                                  \
    F(vkCmdSetLogicOpEXT)                                                                          \
    F(vkCmdSetPrimitiveRestartEnableEXT)                                                           \
    F(vkCmdSetColorWriteEnableEXT)                                                                 \
    F(vkCmdDrawMultiEXT)                                                                           \
    F(vkCmdDrawMultiIndexedEXT)                                                                    \
    F(vkCreateMicromapEXT)                                                                         \
    F(vkDestroyMicromapEXT)                                                                        \
    F(vkCmdBuildMicromapsEXT)                                                                      \
    F(vkBuildMicromapsEXT)                                                                         \
    F(vkCopyMicromapEXT)                                                                           \
    F(vkCopyMicromapToMemoryEXT)                                                                   \
    F(vkCopyMemoryToMicromapEXT)                                                                   \
    F(vkWriteMicromapsPropertiesEXT)                                                               \
    F(vkCmdCopyMicromapEXT)                                                                        \
    F(vkCmdCopyMicromapToMemoryEXT)                                                                \
    F(vkCmdCopyMemoryToMicromapEXT)                                                                \
    F(vkCmdWriteMicromapsPropertiesEXT)                                                            \
    F(vkGetDeviceMicromapCompatibilityEXT)                                                         \
    F(vkGetMicromapBuildSizesEXT)                                                                  \
    F(vkCmdDrawClusterHUAWEI)                                                                      \
    F(vkCmdDrawClusterIndirectHUAWEI)                                                              \
    F(vkSetDeviceMemoryPriorityEXT)                                                                \
    F(vkGetDescriptorSetLayoutHostMappingInfoVALVE)                                                \
    F(vkGetDescriptorSetHostMappingVALVE)                                                          \
    F(vkCmdCopyMemoryIndirectNV)                                                                   \
    F(vkCmdCopyMemoryToImageIndirectNV)                                                            \
    F(vkCmdDecompressMemoryNV)                                                                     \
    F(vkCmdDecompressMemoryIndirectCountNV)                                                        \
    F(vkGetPipelineIndirectMemoryRequirementsNV)                                                   \
    F(vkCmdUpdatePipelineIndirectBufferNV)                                                         \
    F(vkGetPipelineIndirectDeviceAddressNV)                                                        \
    F(vkCmdSetDepthClampEnableEXT)                                                                 \
    F(vkCmdSetPolygonModeEXT)                                                                      \
    F(vkCmdSetRasterizationSamplesEXT)                                                             \
    F(vkCmdSetSampleMaskEXT)                                                                       \
    F(vkCmdSetAlphaToCoverageEnableEXT)                                                            \
    F(vkCmdSetAlphaToOneEnableEXT)                                                                 \
    F(vkCmdSetLogicOpEnableEXT)                                                                    \
    F(vkCmdSetColorBlendEnableEXT)                                                                 \
    F(vkCmdSetColorBlendEquationEXT)                                                               \
    F(vkCmdSetColorWriteMaskEXT)                                                                   \
    F(vkCmdSetTessellationDomainOriginEXT)                                                         \
    F(vkCmdSetRasterizationStreamEXT)                                                              \
    F(vkCmdSetConservativeRasterizationModeEXT)                                                    \
    F(vkCmdSetExtraPrimitiveOverestimationSizeEXT)                                                 \
    F(vkCmdSetDepthClipEnableEXT)                                                                  \
    F(vkCmdSetSampleLocationsEnableEXT)                                                            \
    F(vkCmdSetColorBlendAdvancedEXT)                                                               \
    F(vkCmdSetProvokingVertexModeEXT)                                                              \
    F(vkCmdSetLineRasterizationModeEXT)                                                            \
    F(vkCmdSetLineStippleEnableEXT)                                                                \
    F(vkCmdSetDepthClipNegativeOneToOneEXT)                                                        \
    F(vkCmdSetViewportWScalingEnableNV)                                                            \
    F(vkCmdSetViewportSwizzleNV)                                                                   \
    F(vkCmdSetCoverageToColorEnableNV)                                                             \
    F(vkCmdSetCoverageToColorLocationNV)                                                           \
    F(vkCmdSetCoverageModulationModeNV)                                                            \
    F(vkCmdSetCoverageModulationTableEnableNV)                                                     \
    F(vkCmdSetCoverageModulationTableNV)                                                           \
    F(vkCmdSetShadingRateImageEnableNV)                                                            \
    F(vkCmdSetRepresentativeFragmentTestEnableNV)                                                  \
    F(vkCmdSetCoverageReductionModeNV)                                                             \
    F(vkGetShaderModuleIdentifierEXT)                                                              \
    F(vkGetShaderModuleCreateInfoIdentifierEXT)                                                    \
    F(vkGetPhysicalDeviceOpticalFlowImageFormatsNV)                                                \
    F(vkCreateOpticalFlowSessionNV)                                                                \
    F(vkDestroyOpticalFlowSessionNV)                                                               \
    F(vkBindOpticalFlowSessionImageNV)                                                             \
    F(vkCmdOpticalFlowExecuteNV)                                                                   \
    F(vkAntiLagUpdateAMD)                                                                          \
    F(vkCreateShadersEXT)                                                                          \
    F(vkDestroyShaderEXT)                                                                          \
    F(vkGetShaderBinaryDataEXT)                                                                    \
    F(vkCmdBindShadersEXT)                                                                         \
    F(vkCmdSetDepthClampRangeEXT)                                                                  \
    F(vkGetFramebufferTilePropertiesQCOM)                                                          \
    F(vkGetDynamicRenderingTilePropertiesQCOM)                                                     \
    F(vkGetPhysicalDeviceCooperativeVectorPropertiesNV)                                            \
    F(vkConvertCooperativeVectorMatrixNV)                                                          \
    F(vkCmdConvertCooperativeVectorMatrixNV)                                                       \
    F(vkSetLatencySleepModeNV)                                                                     \
    F(vkLatencySleepNV)                                                                            \
    F(vkSetLatencyMarkerNV)                                                                        \
    F(vkGetLatencyTimingsNV)                                                                       \
    F(vkQueueNotifyOutOfBandNV)                                                                    \
    F(vkCmdSetAttachmentFeedbackLoopEnableEXT)                                                     \
    F(vkCmdBindTileMemoryQCOM)                                                                     \
    F(vkCreateExternalComputeQueueNV)                                                              \
    F(vkDestroyExternalComputeQueueNV)                                                             \
    F(vkGetExternalComputeQueueDataNV)                                                             \
    F(vkGetClusterAccelerationStructureBuildSizesNV)                                               \
    F(vkCmdBuildClusterAccelerationStructureIndirectNV)                                            \
    F(vkGetPartitionedAccelerationStructuresBuildSizesNV)                                          \
    F(vkCmdBuildPartitionedAccelerationStructuresNV)                                               \
    F(vkGetGeneratedCommandsMemoryRequirementsEXT)                                                 \
    F(vkCmdPreprocessGeneratedCommandsEXT)                                                         \
    F(vkCmdExecuteGeneratedCommandsEXT)                                                            \
    F(vkCreateIndirectCommandsLayoutEXT)                                                           \
    F(vkDestroyIndirectCommandsLayoutEXT)                                                          \
    F(vkCreateIndirectExecutionSetEXT)                                                             \
    F(vkDestroyIndirectExecutionSetEXT)                                                            \
    F(vkUpdateIndirectExecutionSetPipelineEXT)                                                     \
    F(vkUpdateIndirectExecutionSetShaderEXT)                                                       \
    F(vkGetPhysicalDeviceCooperativeMatrixFlexibleDimensionsPropertiesNV)                          \
    F(vkCmdEndRendering2EXT)                                                                       \
    F(vkCreateAccelerationStructureKHR)                                                            \
    F(vkDestroyAccelerationStructureKHR)                                                           \
    F(vkCmdBuildAccelerationStructuresKHR)                                                         \
    F(vkCmdBuildAccelerationStructuresIndirectKHR)                                                 \
    F(vkBuildAccelerationStructuresKHR)                                                            \
    F(vkCopyAccelerationStructureKHR)                                                              \
    F(vkCopyAccelerationStructureToMemoryKHR)                                                      \
    F(vkCopyMemoryToAccelerationStructureKHR)                                                      \
    F(vkWriteAccelerationStructuresPropertiesKHR)                                                  \
    F(vkCmdCopyAccelerationStructureKHR)                                                           \
    F(vkCmdCopyAccelerationStructureToMemoryKHR)                                                   \
    F(vkCmdCopyMemoryToAccelerationStructureKHR)                                                   \
    F(vkGetAccelerationStructureDeviceAddressKHR)                                                  \
    F(vkCmdWriteAccelerationStructuresPropertiesKHR)                                               \
    F(vkGetDeviceAccelerationStructureCompatibilityKHR)                                            \
    F(vkGetAccelerationStructureBuildSizesKHR)                                                     \
    F(vkCmdTraceRaysKHR)                                                                           \
    F(vkCreateRayTracingPipelinesKHR)                                                              \
    F(vkGetRayTracingCaptureReplayShaderGroupHandlesKHR)                                           \
    F(vkCmdTraceRaysIndirectKHR)                                                                   \
    F(vkGetRayTracingShaderGroupStackSizeKHR)                                                      \
    F(vkCmdSetRayTracingPipelineStackSizeKHR)                                                      \
    F(vkCmdDrawMeshTasksEXT)                                                                       \
    F(vkCmdDrawMeshTasksIndirectEXT)                                                               \
    F(vkCmdDrawMeshTasksIndirectCountEXT)                                                          \
    F(vkCreateWaylandSurfaceKHR)                                                                   \
    F(vkGetPhysicalDeviceWaylandPresentationSupportKHR)                                            \
    F(vkCreateXcbSurfaceKHR)                                                                       \
    F(vkGetPhysicalDeviceXcbPresentationSupportKHR)                                                \
    F(vkCreateXlibSurfaceKHR)                                                                      \
    F(vkGetPhysicalDeviceXlibPresentationSupportKHR)
