#ifndef LORE_BASE_RUNTIMEBASE_GLOBAL_H
#define LORE_BASE_RUNTIMEBASE_GLOBAL_H

#include <LoreBase/CoreLib/Global.h>

#ifndef LORERTBASE_EXPORT
#  ifdef LORERTBASE_STATIC
#    define LORERTBASE_EXPORT
#  else
#    ifdef LORERTBASE_LIBRARY
#      define LORERTBASE_EXPORT LORE_DECL_EXPORT
#    else
#      define LORERTBASE_EXPORT LORE_DECL_IMPORT
#    endif
#  endif
#endif

#endif // LORE_BASE_RUNTIMEBASE_GLOBAL_H
