include "Thunk_config_symbols.conf"

# List guest functions that needs thunks.
["Guest Function"]


# List callbacks that needs thunks.
# If starts with '&', the type is inferred from the function declaration
# of the name, otherwise it is assumed to be a function pointer typedef.
[Callback]
&printf
PFN_scanf
