#ifndef LORE_TOOLS_TLCAPI_DOCUMENTCONTEXT_H
#define LORE_TOOLS_TLCAPI_DOCUMENTCONTEXT_H

#include <map>
#include <string>
#include <cassert>
#include <set>

#include <lorelei/Tools/ToolUtils/SourceLineList.h>
#include <lorelei/Tools/TLCApi/Core/ProcSnippet.h>
#include <lorelei/Tools/TLCApi/Global.h>
#include <lorelei/Tools/TLCApi/Utils/ProcAliasMaker.h>

namespace clang {
    class CompilerInstance;
}

namespace lore::tool::TLC {

    class ManifestStatistics;

    /// DocumentContext - Runtime state container for one TLC `generate` invocation.
    ///
    /// Responsibilities:
    /// 1. Hold immutable input metadata (mode, source file path, manifest stat reference).
    /// 2. Own mutable proc list consumed by TLC passes.
    /// 3. Own document-level source fragments emitted by the generation pipeline.
    /// 4. Accept pre-collected AST metadata from command/main and apply it to procs.
    ///
    /// Non-responsibilities:
    /// 1. AST matching and clang traversal.
    /// 2. Command-line parsing.
    class LORETLCAPI_EXPORT DocumentContext {
    public:
        enum Mode {
            Guest = 0,
            Host = 1,
        };

        struct RequestedProcData {
            std::array<std::set<std::string>, ProcSnippet::NumKinds> functions;
            std::map<std::string /* signature */, std::string /* name */> callbacks;
        };

        struct DocumentSource {
            std::map<std::string, std::string> properties;
            SourceLineList<> head;
            SourceLineList<> tail;
        };

        DocumentContext() = default;
        ~DocumentContext() = default;

        inline void initialize(Mode mode, std::string fileName,
                               RequestedProcData interestedProcData) {
            m_mode = mode;
            m_fileName = fileName;
            m_interestedProcData = std::move(interestedProcData);
        }

        bool beginSourceFileAction(clang::CompilerInstance &CI);
        void handleTranslationUnit(clang::ASTContext &ast);
        void endSourceFileAction();

        void generateOutput(llvm::raw_ostream &os);

    public:
        inline Mode mode() const {
            return m_mode;
        }
        inline std::string fileName() const {
            return m_fileName;
        }
        inline clang::ASTContext &ast() const {
            assert(m_ast != nullptr);
            return *m_ast;
        }

        /// Sources to generate.
        inline DocumentSource &source() {
            return m_source;
        }
        inline const DocumentSource &source() const {
            return m_source;
        }

        /// Proc snippets.
        inline std::map<std::string, ProcSnippet::ProcSource> &
            procs(ProcSnippet::Kind kind, ProcSnippet::Direction direction) {
            return m_procs[kind][direction];
        }
        inline const std::map<std::string, ProcSnippet::ProcSource> &
            procs(ProcSnippet::Kind kind, ProcSnippet::Direction direction) const {
            return m_procs[kind][direction];
        }

    protected:
        Mode m_mode = Guest;
        std::string m_fileName;
        RequestedProcData m_interestedProcData;

        // AST data
        clang::ASTContext *m_ast = nullptr;
        std::array<std::map<std::string, const clang::FunctionDecl *>, ProcSnippet::NumKinds>
            m_functionDecls;
        std::map<std::string, const clang::VarDecl *> m_varDecls;

        // Generated by passes
        DocumentSource m_source;
        std::array<
            std::array<std::map<std::string, ProcSnippet::ProcSource>, ProcSnippet::NumDirections>,
            ProcSnippet::NumKinds>
            m_procs;

        // Helpers
        ProcAliasMaker m_procAliasMaker;
    };

}

#endif // LORE_TOOLS_TLCAPI_DOCUMENTCONTEXT_H
